/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import dao.AlunoDAO;
import dao.TurmaDAO;
import entities.Aluno;
import entities.Professor;
import entities.Turma;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author melys
 */
public class FormAlunos extends javax.swing.JFrame {
    
    private void preenchercmbTurma(){
        TurmaDAO turmaDAO  = new TurmaDAO();
        List<Turma> lista = turmaDAO.pesquisarTurmas2("");
        
        for(Turma t: lista){
            cmbTurma.addItem(t);
    
}
    }
    /**
     * Creates new form FormAlunos
     */
    public FormAlunos() {
        initComponents();
        preenchercmbTurma();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNomeMae = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNomePai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbTurma = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Formulário de Alunos");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 0, 51));
        jLabel2.setText("Pesquisar ID do Aluno:");

        txtIdPesquisa.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtIdPesquisa.setForeground(new java.awt.Color(0, 102, 102));

        btnPesquisar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(0, 102, 102));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 0, 51));
        jLabel3.setText("ID:");
        jLabel3.setToolTipText("");

        txtId.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 102, 102));
        txtId.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 0, 51));
        jLabel4.setText("Nome do Aluno:");
        jLabel4.setToolTipText("");

        txtNomeAluno.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtNomeAluno.setForeground(new java.awt.Color(0, 102, 102));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 0, 51));
        jLabel5.setText("Nome da Mãe:");
        jLabel5.setToolTipText("");

        txtNomeMae.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtNomeMae.setForeground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 0, 51));
        jLabel6.setText("Nome do Pai:");
        jLabel6.setToolTipText("");

        txtNomePai.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtNomePai.setForeground(new java.awt.Color(0, 102, 102));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 0, 51));
        jLabel7.setText("Data de Nascimento:");
        jLabel7.setToolTipText("");

        txtDataNasc.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtDataNasc.setForeground(new java.awt.Color(0, 102, 102));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 0, 51));
        jLabel8.setText("Data de Cadastro:");
        jLabel8.setToolTipText("");

        txtDataCadastro.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        txtDataCadastro.setForeground(new java.awt.Color(0, 102, 102));

        btnCadastrar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 102, 102));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnRelatorio.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(0, 102, 102));
        btnRelatorio.setText("Relatório de Alunos");
        btnRelatorio.setToolTipText("");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(0, 102, 102));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setToolTipText("");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(0, 102, 102));
        btnDeletar.setText("Deletar");
        btnDeletar.setToolTipText("");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(251, 0, 51));
        jLabel9.setText("Turma:");
        jLabel9.setToolTipText("");

        cmbTurma.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cmbTurma.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeAluno)
                            .addComponent(txtNomeMae)
                            .addComponent(txtNomePai, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(txtDataCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(txtDataNasc)
                            .addComponent(cmbTurma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(5, 5, 5)
                        .addComponent(btnRelatorio)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnRelatorio)
                    .addComponent(btnAtualizar)
                    .addComponent(btnDeletar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nomeAluno = txtNomeAluno.getText();
        String nomeMae = txtNomeMae.getText();
        String nomePai = txtNomePai.getText();
        String dataNasc = txtDataNasc.getText();
        String dataCadastro = txtDataCadastro.getText();
        Turma turma_id  = (Turma) cmbTurma.getSelectedItem();
        
        Aluno aluno = new Aluno();
        aluno.setNome(nomeAluno);
        aluno.setNome_mae(nomeMae);
        aluno.setNome_pai(nomePai);
        aluno.setDt_nasc(dataNasc);
        aluno.setDt_cadastro(dataCadastro);
        aluno.setTurma_id(turma_id);
        
        AlunoDAO alunoDAO = new AlunoDAO();
        alunoDAO.adicionarAluno(aluno);
        
        txtNomeAluno.setText("");
        txtNomeMae.setText("");
        txtNomePai.setText("");
        txtDataNasc.setText("");
        txtDataCadastro.setText("");
        
        JOptionPane.showMessageDialog(this, "Cadastro realizado.");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        int idPesquisa = Integer.parseInt(txtIdPesquisa.getText());
        AlunoDAO alunoDAO = new AlunoDAO();
        Aluno aluno = alunoDAO.pesquisaAluno(idPesquisa);
        if(aluno == null) {
            JOptionPane.showMessageDialog(this, "Aluno não encontrado");
        }
        else {
            txtId.setText(String.valueOf(aluno.getId()));
            txtNomeAluno.setText(aluno.getNome());
            txtNomeMae.setText(aluno.getNome_mae());
            txtNomePai.setText(aluno.getNome_pai());
            txtDataNasc.setText(aluno.getDt_nasc());
            txtDataCadastro.setText(aluno.getDt_cadastro());
            cmbTurma.setSelectedItem(aluno.getTurma_id());
        }
     
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        int id = Integer.parseInt(txtIdPesquisa.getText());
        String nomeAluno = txtNomeAluno.getText();
        String nomeMae = txtNomeMae.getText();
        String nomePai = txtNomePai.getText();
        String dataNasc = txtDataNasc.getText();
        String dataCadastro = txtDataCadastro.getText();
        Turma turma_id  = (Turma) cmbTurma.getSelectedItem();
        
        Aluno aluno = new Aluno();
        aluno.setId(id);
        aluno.setNome(nomeAluno);
        aluno.setNome_mae(nomeMae);
        aluno.setNome_pai(nomePai);
        aluno.setDt_nasc(dataNasc);
        aluno.setDt_cadastro(dataCadastro);
        aluno.setTurma_id(turma_id);
        
        AlunoDAO alunoDAO = new AlunoDAO();
        alunoDAO.atualizarAluno(aluno);
        
        txtNomeAluno.setText("");
        txtNomeMae.setText("");
        txtNomePai.setText("");
        txtDataNasc.setText("");
        txtDataCadastro.setText("");
        
        JOptionPane.showMessageDialog(this, "Cadastro atualizado.");
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int id = Integer.parseInt(txtId.getText());
        AlunoDAO alunoDAO = new AlunoDAO();
        alunoDAO.deletarAluno(id);
        
        txtNomeAluno.setText("");
        txtNomeMae.setText("");
        txtNomePai.setText("");
        txtDataNasc.setText("");
        txtDataCadastro.setText("");
        
        JOptionPane.showMessageDialog(this, "Cadastro excluído.");
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        FormRelatorioAlunos form_ra = new FormRelatorioAlunos();
        form_ra.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JComboBox cmbTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPesquisa;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtNomePai;
    // End of variables declaration//GEN-END:variables
}
